const API_BASE_URL = "https://postureio-backend.onrender.com";

const elements = {
  apiKey: document.getElementById("apiKey"),
  saveKeyBtn: document.getElementById("saveKeyBtn"),
  keyStatus: document.getElementById("keyStatus"),
  refreshBtn: document.getElementById("refreshBtn"),
  backendStatus: document.getElementById("backendStatus"),
  backendMessage: document.getElementById("backendMessage"),
  currentPosture: document.getElementById("currentPosture"),
  currentPostureMeta: document.getElementById("currentPostureMeta"),
  riskLevel: document.getElementById("riskLevel"),
  riskMessage: document.getElementById("riskMessage"),
  aiSource: document.getElementById("aiSource"),
  aiAdvice: document.getElementById("aiAdvice"),
  totalReadings: document.getElementById("totalReadings"),
  badPosture: document.getElementById("badPosture"),
  goodPosture: document.getElementById("goodPosture"),
  mostCommon: document.getElementById("mostCommon"),
  historyTable: document.getElementById("historyTable")
};

function getApiKey() {
  return sessionStorage.getItem("dashboard_api_key");
}

function saveApiKey() {
  const value = elements.apiKey.value.trim();

  if (!value) {
    elements.keyStatus.textContent = "Please enter a valid dashboard API key.";
    return;
  }

  sessionStorage.setItem("dashboard_api_key", value);
  elements.apiKey.value = "";
  elements.keyStatus.textContent = "Dashboard API key saved for this session.";
  loadDashboard();
}

async function apiGet(path, requiresAuth = true) {
  const headers = {
    accept: "application/json"
  };

  if (requiresAuth) {
    const apiKey = getApiKey();

    if (!apiKey) {
      throw new Error("Missing dashboard API key.");
    }

    headers["x-api-key"] = apiKey;
  }

  const response = await fetch(`${API_BASE_URL}${path}`, { headers });

  if (!response.ok) {
    throw new Error(`Request failed: ${response.status}`);
  }

  return response.json();
}

async function loadHealth() {
  const data = await apiGet("/api/device/health", false);

  elements.backendStatus.textContent = data.status;
  elements.backendMessage.textContent = data.message;
}

async function loadLatestReading() {
  const data = await apiGet("/api/readings/latest");

  if (!data) {
    elements.currentPosture.textContent = "--";
    elements.currentPostureMeta.textContent = "No readings available.";
    return;
  }

  elements.currentPosture.textContent = data.posture.replaceAll("_", " ");
  elements.currentPostureMeta.textContent = `Confidence ${(data.confidence * 100).toFixed(0)}% · ${data.device_id}`;
}

async function loadSummary() {
  const data = await apiGet("/api/reports/summary");

  elements.totalReadings.textContent = data.total_readings ?? "--";
  elements.badPosture.textContent = `${data.bad_posture_percentage ?? 0}%`;
  elements.goodPosture.textContent = `${data.good_posture_percentage ?? 0}%`;
  elements.mostCommon.textContent = data.most_common_posture
    ? data.most_common_posture.replaceAll("_", " ")
    : "--";
}

async function loadAiAdvice() {
  const data = await apiGet("/api/advice/ai");

  elements.riskLevel.textContent = data.risk_level ?? "--";
  elements.riskMessage.textContent = data.summary
    ? `${data.summary.bad_posture_percentage}% bad posture detected.`
    : "No summary available.";

  elements.aiSource.textContent = data.source === "gemini"
    ? "Generated by Gemini"
    : "Generated by local engine";

  elements.aiAdvice.textContent = data.advice ?? "No advice available.";
}

async function loadHistory() {
  const data = await apiGet("/api/readings/history?limit=10");

  if (!data.length) {
    elements.historyTable.innerHTML = `
      <tr>
        <td colspan="7">No readings available.</td>
      </tr>
    `;
    return;
  }

  elements.historyTable.innerHTML = data.map((item) => `
    <tr>
      <td>${item.id}</td>
      <td>${item.device_id}</td>
      <td>${item.user_id}</td>
      <td>${item.posture.replaceAll("_", " ")}</td>
      <td>${item.is_bad_posture ? "Yes" : "No"}</td>
      <td>${(item.confidence * 100).toFixed(0)}%</td>
      <td>${new Date(item.created_at).toLocaleString()}</td>
    </tr>
  `).join("");
}

async function loadDashboard() {
  try {
    await loadHealth();

    if (!getApiKey()) {
      elements.keyStatus.textContent = "Enter your dashboard API key to load protected data.";
      return;
    }

    await Promise.all([
      loadLatestReading(),
      loadSummary(),
      loadAiAdvice(),
      loadHistory()
    ]);
  } catch (error) {
    elements.keyStatus.textContent = error.message;
  }
}

elements.saveKeyBtn.addEventListener("click", saveApiKey);
elements.refreshBtn.addEventListener("click", loadDashboard);

loadDashboard();