const API_BASE_URL = "https://postureio-backend.onrender.com";

let historyLimit = 10;
let latestReadingCache = null;
let summaryCache = null;
let adviceCache = null;
let historyCache = [];
let currentLanguage = localStorage.getItem("dashboard_language") || "en";

const translations = {
  en: {
    eyebrow: "IoT Posture Monitoring",
    subtitle: "Real-time posture insights from Arduino/ESP32 sensor readings.",
    dashboardApiKey: "Dashboard API Key",
    apiKeyPlaceholder: "Enter dashboard API key",
    connected: "Connected",
    notConnected: "Not connected",
    save: "Save",
    backend: "Backend",
    currentPosture: "Current Posture",
    riskLevel: "Risk Level",
    aiRecommendation: "AI Recommendation",
    postureAdvice: "Posture Advice",
    summary: "Summary",
    postureReport: "Posture Report",
    totalReadings: "Total readings",
    badPosture: "Bad posture",
    goodPosture: "Good posture",
    mostCommon: "Most common",
    sensorFeed: "Sensor Feed",
    latestReadings: "Latest Readings",
    refresh: "Refresh",
    loadAll: "Load all",
    showLatest: "Show latest 10",
    tableNo: "No.",
    tableDevice: "Device",
    tableUser: "User",
    tablePosture: "Posture",
    tableBad: "Bad",
    tableConfidence: "Confidence",
    tableTime: "Guatemala timezone",
    keyStored: "Key is stored only in this browser session.",
    keySaved: "Dashboard API key saved for this session.",
    keyRequired: "Enter your dashboard API key to load protected data.",
    keyInvalid: "Please enter a valid dashboard API key.",
    missingKey: "Missing dashboard API key.",
    waitingApi: "Waiting for API response.",
    ready: "ready",
    running: "running",
    deviceCanSendReadings: "Device can send readings to /api/readings",
    noReadingLoaded: "No reading loaded yet.",
    noReadings: "No readings available.",
    noDataLoaded: "No data loaded yet.",
    aiNotLoaded: "AI advice not loaded yet.",
    generatingAdvice: "Generating posture recommendation...",
    addKeyAdvice: "Add your dashboard API key and refresh data.",
    noAdvice: "No advice available.",
    noSummary: "No summary available.",
    confidence: "Confidence",
    generatedByGemini: "Generated by Gemini",
    localFallback: "Local recommendation",
    generating: "Generating...",
    badPostureDetected: "{value}% bad posture detected.",
    latestHelper: "Showing latest {count} readings from newest to oldest. Use “Load all” to view the full history.",
    allHelper: "Showing full history. {count} readings loaded from newest to oldest.",
    yes: "Yes",
    no: "No",
    adviceUnknown: "There is not enough posture data yet to generate a recommendation.",
    adviceHigh: "High posture risk detected. The most frequent issue is {posture}. Adjust your chair, sit centered, support your back, and take a short break.",
    adviceMedium: "Moderate posture risk detected. You often sit in {posture}. Try to balance your weight, keep both feet on the floor, and correct your back position.",
    adviceLow: "Posture behavior looks stable. Keep a balanced sitting position and continue taking regular breaks."
  },
  es: {
    eyebrow: "Monitoreo IoT de Postura",
    subtitle: "Lecturas de postura en tiempo real desde Arduino/ESP32.",
    dashboardApiKey: "Clave del Dashboard",
    apiKeyPlaceholder: "Ingresá la clave del dashboard",
    connected: "Conectado",
    notConnected: "No conectado",
    save: "Guardar",
    backend: "Backend",
    currentPosture: "Postura Actual",
    riskLevel: "Nivel de Riesgo",
    aiRecommendation: "Recomendación IA",
    postureAdvice: "Consejo de Postura",
    summary: "Resumen",
    postureReport: "Reporte de Postura",
    totalReadings: "Lecturas totales",
    badPosture: "Mala postura",
    goodPosture: "Buena postura",
    mostCommon: "Más común",
    sensorFeed: "Lecturas del Sensor",
    latestReadings: "Últimas Lecturas",
    refresh: "Actualizar",
    loadAll: "Cargar todo",
    showLatest: "Ver últimos 10",
    tableNo: "No.",
    tableDevice: "Dispositivo",
    tableUser: "Usuario",
    tablePosture: "Postura",
    tableBad: "Incorrecta",
    tableConfidence: "Confianza",
    tableTime: "Hora Guatemala",
    keyStored: "La clave se guarda solo en esta sesión del navegador.",
    keySaved: "Clave del dashboard guardada para esta sesión.",
    keyRequired: "Ingresá la clave del dashboard para cargar datos protegidos.",
    keyInvalid: "Ingresá una clave válida del dashboard.",
    missingKey: "Falta la clave del dashboard.",
    waitingApi: "Esperando respuesta de la API.",
    ready: "listo",
    running: "activo",
    deviceCanSendReadings: "El dispositivo puede enviar lecturas a /api/readings",
    noReadingLoaded: "Aún no se ha cargado ninguna lectura.",
    noReadings: "No hay lecturas disponibles.",
    noDataLoaded: "No hay datos cargados todavía.",
    aiNotLoaded: "El consejo de IA aún no se ha cargado.",
    generatingAdvice: "Generando recomendación de postura...",
    addKeyAdvice: "Agregá la clave del dashboard y actualizá los datos.",
    noAdvice: "No hay consejo disponible.",
    noSummary: "No hay resumen disponible.",
    confidence: "Confianza",
    generatedByGemini: "Generado por Gemini",
    localFallback: "Recomendación local",
    generating: "Generando...",
    badPostureDetected: "{value}% de mala postura detectada.",
    latestHelper: "Mostrando las últimas {count} lecturas, de la más reciente a la más antigua. Usá “Cargar todo” para ver el historial completo.",
    allHelper: "Mostrando historial completo. {count} lecturas cargadas de la más reciente a la más antigua.",
    yes: "Sí",
    no: "No",
    adviceUnknown: "Aún no hay suficientes lecturas de postura para generar una recomendación.",
    adviceHigh: "Riesgo postural alto detectado. La postura más frecuente es {posture}. Ajustá tu silla, sentate centrado, apoyá la espalda y tomá una pausa corta.",
    adviceMedium: "Riesgo postural moderado detectado. Frecuentemente estás en postura {posture}. Intentá balancear tu peso, mantener ambos pies en el suelo y corregir tu espalda.",
    adviceLow: "El comportamiento postural se ve estable. Mantené una posición balanceada y seguí tomando pausas regulares."
  }
};

const postureTranslations = {
  en: {
    correct: "correct",
    leaning_left: "leaning left",
    leaning_right: "leaning right",
    leaning_forward: "leaning forward",
    leaning_back: "leaning back",
    slouched: "slouched",
    not_sitting: "not sitting"
  },
  es: {
    correct: "correcta",
    leaning_left: "inclinado a la izquierda",
    leaning_right: "inclinado a la derecha",
    leaning_forward: "inclinado hacia adelante",
    leaning_back: "inclinado hacia atrás",
    slouched: "encorvado",
    not_sitting: "sin persona sentada"
  }
};

const riskTranslations = {
  en: {
    low: "low",
    medium: "medium",
    high: "high",
    unknown: "unknown"
  },
  es: {
    low: "bajo",
    medium: "medio",
    high: "alto",
    unknown: "desconocido"
  }
};

const backendStatusTranslations = {
  ready: "ready",
  running: "running"
};

const backendMessageTranslations = {
  "Device can send readings to /api/readings": "deviceCanSendReadings"
};

const elements = {
  apiKey: document.getElementById("apiKey"),
  saveKeyBtn: document.getElementById("saveKeyBtn"),
  keyStatus: document.getElementById("keyStatus"),
  keyPanelStatus: document.getElementById("keyPanelStatus"),
  apiKeyPanel: document.getElementById("apiKeyPanel"),
  langEnBtn: document.getElementById("langEnBtn"),
  langEsBtn: document.getElementById("langEsBtn"),
  refreshBtn: document.getElementById("refreshBtn"),
  loadAllBtn: document.getElementById("loadAllBtn"),
  backendCard: document.getElementById("backendCard"),
  currentPostureCard: document.getElementById("currentPostureCard"),
  riskCard: document.getElementById("riskCard"),
  backendStatus: document.getElementById("backendStatus"),
  backendMessage: document.getElementById("backendMessage"),
  currentPosture: document.getElementById("currentPosture"),
  currentPostureMeta: document.getElementById("currentPostureMeta"),
  riskLevel: document.getElementById("riskLevel"),
  riskMessage: document.getElementById("riskMessage"),
  aiSource: document.getElementById("aiSource"),
  aiAdvice: document.getElementById("aiAdvice"),
  totalReadings: document.getElementById("totalReadings"),
  badPosture: document.getElementById("badPosture"),
  goodPosture: document.getElementById("goodPosture"),
  mostCommon: document.getElementById("mostCommon"),
  historyTable: document.getElementById("historyTable"),
  historyHelper: document.getElementById("historyHelper")
};

function t(key, replacements = {}) {
  let value = translations[currentLanguage][key] || key;

  Object.entries(replacements).forEach(([placeholder, replacement]) => {
    value = value.replace(`{${placeholder}}`, replacement);
  });

  return value;
}

function getApiKey() {
  return sessionStorage.getItem("dashboard_api_key");
}

function setStatusClass(element, status) {
  element.classList.remove("status-good", "status-warning", "status-danger", "status-neutral");
  element.classList.add(status);
}

function formatPosture(value) {
  if (!value) {
    return "--";
  }

  return postureTranslations[currentLanguage][value] || value.replaceAll("_", " ");
}

function formatRiskLevel(value) {
  if (!value) {
    return "--";
  }

  return riskTranslations[currentLanguage][value] || value;
}

function formatBackendStatus(value) {
  const translationKey = backendStatusTranslations[value];

  if (!translationKey) {
    return value;
  }

  return t(translationKey);
}

function formatBackendMessage(value) {
  const translationKey = backendMessageTranslations[value];

  if (!translationKey) {
    return value;
  }

  return t(translationKey);
}

function formatGuatemalaTime(value) {
  if (!value) {
    return "--";
  }

  const timestamp = value.endsWith("Z") ? value : `${value}Z`;

  return new Intl.DateTimeFormat("en-US", {
    timeZone: "America/Guatemala",
    month: "numeric",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
    second: "2-digit",
    hour12: true
  }).format(new Date(timestamp));
}

function buildLocalizedAdvice(data) {
  const summary = data.summary || {};
  const riskLevel = data.risk_level || "unknown";
  const posture = formatPosture(summary.most_common_posture);

  if (!summary.total_readings) {
    return t("adviceUnknown");
  }

  if (riskLevel === "high") {
    return t("adviceHigh", { posture });
  }

  if (riskLevel === "medium") {
    return t("adviceMedium", { posture });
  }

  if (riskLevel === "low") {
    return t("adviceLow");
  }

  return t("adviceUnknown");
}

function getAdviceText(data) {
  const responseLanguage = data.language || null;
  const canUseGeminiText = data.source === "gemini" && responseLanguage === currentLanguage;

  if (canUseGeminiText && data.advice) {
    return data.advice;
  }

  return buildLocalizedAdvice(data);
}

function applyStaticTranslations() {
  document.documentElement.lang = currentLanguage;

  document.querySelectorAll("[data-i18n]").forEach((item) => {
    const key = item.getAttribute("data-i18n");
    item.textContent = t(key);
  });

  document.querySelectorAll("[data-i18n-placeholder]").forEach((item) => {
    const key = item.getAttribute("data-i18n-placeholder");
    item.setAttribute("placeholder", t(key));
  });

  elements.langEnBtn.classList.toggle("active", currentLanguage === "en");
  elements.langEsBtn.classList.toggle("active", currentLanguage === "es");

  elements.loadAllBtn.textContent = historyLimit === 1000
    ? t("showLatest")
    : t("loadAll");
}

function updateKeyPanelState() {
  const hasKey = Boolean(getApiKey());

  if (hasKey) {
    elements.apiKeyPanel.classList.add("connected");
    elements.keyPanelStatus.textContent = t("connected");
    elements.keyStatus.textContent = t("keySaved");
    elements.apiKeyPanel.open = false;
    return;
  }

  elements.apiKeyPanel.classList.remove("connected");
  elements.keyPanelStatus.textContent = t("notConnected");
  elements.keyStatus.textContent = t("keyRequired");
  elements.apiKeyPanel.open = true;
}

function saveApiKey() {
  const value = elements.apiKey.value.trim();

  if (!value) {
    elements.keyStatus.textContent = t("keyInvalid");
    return;
  }

  sessionStorage.setItem("dashboard_api_key", value);
  elements.apiKey.value = "";
  elements.apiKeyPanel.classList.add("saved");

  setTimeout(() => {
    elements.apiKeyPanel.classList.remove("saved");
  }, 450);

  updateKeyPanelState();
  loadDashboard();
}

function setLanguage(language) {
  if (language === currentLanguage) {
    return;
  }

  currentLanguage = language;
  localStorage.setItem("dashboard_language", language);

  applyStaticTranslations();
  updateKeyPanelState();
  renderCachedDashboard();

  if (!getApiKey()) {
    elements.backendMessage.textContent = t("waitingApi");
    elements.currentPostureMeta.textContent = t("noReadingLoaded");
    elements.riskMessage.textContent = t("aiNotLoaded");
    elements.aiAdvice.textContent = t("addKeyAdvice");
    elements.historyHelper.textContent = t("latestHelper", { count: 10 });
  }
}

async function apiGet(path, requiresAuth = true) {
  const headers = {
    accept: "application/json"
  };

  if (requiresAuth) {
    const apiKey = getApiKey();

    if (!apiKey) {
      throw new Error(t("missingKey"));
    }

    headers["x-api-key"] = apiKey;
  }

  const response = await fetch(`${API_BASE_URL}${path}`, { headers });

  if (!response.ok) {
    throw new Error(`Request failed: ${response.status}`);
  }

  return response.json();
}

async function loadHealth() {
  const data = await apiGet("/api/device/health", false);

  elements.backendStatus.textContent = formatBackendStatus(data.status);
  elements.backendMessage.textContent = formatBackendMessage(data.message);

  if (data.status === "ready" || data.status === "running") {
    setStatusClass(elements.backendCard, "status-good");
  } else {
    setStatusClass(elements.backendCard, "status-warning");
  }
}

function renderLatestReading(data) {
  if (!data) {
    elements.currentPosture.textContent = "--";
    elements.currentPostureMeta.textContent = t("noReadings");
    setStatusClass(elements.currentPostureCard, "status-neutral");
    return;
  }

  elements.currentPosture.textContent = formatPosture(data.posture);
  elements.currentPostureMeta.textContent = `${t("confidence")} ${(data.confidence * 100).toFixed(0)}% · ${data.device_id}`;

  if (data.posture === "correct" && !data.is_bad_posture) {
    setStatusClass(elements.currentPostureCard, "status-good");
  } else if (data.posture === "not_sitting") {
    setStatusClass(elements.currentPostureCard, "status-warning");
  } else {
    setStatusClass(elements.currentPostureCard, "status-danger");
  }
}

async function loadLatestReading() {
  const data = await apiGet("/api/readings/latest");
  latestReadingCache = data;
  renderLatestReading(data);
}

function renderSummary(data) {
  elements.totalReadings.textContent = data.total_readings ?? "--";
  elements.badPosture.textContent = `${data.bad_posture_percentage ?? 0}%`;
  elements.goodPosture.textContent = `${data.good_posture_percentage ?? 0}%`;
  elements.mostCommon.textContent = data.most_common_posture
    ? formatPosture(data.most_common_posture)
    : "--";
}

async function loadSummary() {
  const data = await apiGet("/api/reports/summary");
  summaryCache = data;
  renderSummary(data);
}

function renderAiAdvice(data) {
  elements.riskLevel.textContent = formatRiskLevel(data.risk_level);
  elements.riskMessage.textContent = data.summary
    ? t("badPostureDetected", { value: data.summary.bad_posture_percentage })
    : t("noSummary");

  if (data.risk_level === "low") {
    setStatusClass(elements.riskCard, "status-good");
  } else if (data.risk_level === "medium") {
    setStatusClass(elements.riskCard, "status-warning");
  } else if (data.risk_level === "high") {
    setStatusClass(elements.riskCard, "status-danger");
  } else {
    setStatusClass(elements.riskCard, "status-neutral");
  }

  elements.aiSource.classList.remove("gemini", "local");

  const responseLanguage = data.language || null;
  const canUseGeminiText = data.source === "gemini" && responseLanguage === currentLanguage;

  if (canUseGeminiText) {
    elements.aiSource.textContent = t("generatedByGemini");
    elements.aiSource.classList.add("gemini");
  } else {
    elements.aiSource.textContent = t("localFallback");
    elements.aiSource.classList.add("local");
  }

  elements.aiAdvice.textContent = getAdviceText(data);
}

async function loadAiAdvice() {
  elements.aiSource.classList.remove("gemini", "local");
  elements.aiSource.textContent = t("generating");
  elements.aiAdvice.textContent = t("generatingAdvice");

  const data = await apiGet(`/api/advice/ai?lang=${currentLanguage}`);
  adviceCache = data;
  renderAiAdvice(data);
}

function renderHistory(data) {
  const isShowingAll = historyLimit === 1000;

  elements.historyHelper.textContent = isShowingAll
    ? t("allHelper", { count: data.length })
    : t("latestHelper", { count: data.length });

  elements.loadAllBtn.textContent = isShowingAll ? t("showLatest") : t("loadAll");

  if (!data.length) {
    elements.historyTable.innerHTML = `
      <tr>
        <td colspan="7">${t("noReadings")}</td>
      </tr>
    `;
    return;
  }

  elements.historyTable.innerHTML = data.map((item, index) => `
    <tr>
      <td>${data.length - index}</td>
      <td>${item.device_id}</td>
      <td>${item.user_id}</td>
      <td>${formatPosture(item.posture)}</td>
      <td>${item.is_bad_posture ? t("yes") : t("no")}</td>
      <td>${(item.confidence * 100).toFixed(0)}%</td>
      <td>${formatGuatemalaTime(item.created_at)}</td>
    </tr>
  `).join("");
}

async function loadHistory() {
  const data = await apiGet(`/api/readings/history?limit=${historyLimit}`);
  historyCache = data;
  renderHistory(data);
}

function renderCachedDashboard() {
  if (latestReadingCache) {
    renderLatestReading(latestReadingCache);
  }

  if (summaryCache) {
    renderSummary(summaryCache);
  }

  if (adviceCache) {
    renderAiAdvice(adviceCache);
  }

  if (historyCache.length) {
    renderHistory(historyCache);
  }
}

async function loadDashboard() {
  try {
    await loadHealth();

    if (!getApiKey()) {
      updateKeyPanelState();
      return;
    }

    await Promise.all([
      loadLatestReading(),
      loadSummary(),
      loadAiAdvice(),
      loadHistory()
    ]);

    updateKeyPanelState();
  } catch (error) {
    elements.keyStatus.textContent = error.message;
  }
}

elements.saveKeyBtn.addEventListener("click", saveApiKey);

elements.refreshBtn.addEventListener("click", () => {
  historyLimit = 10;
  historyCache = [];
  loadDashboard();
});

elements.loadAllBtn.addEventListener("click", () => {
  historyLimit = historyLimit === 1000 ? 10 : 1000;
  loadHistory();
});

elements.langEnBtn.addEventListener("click", () => {
  setLanguage("en");
});

elements.langEsBtn.addEventListener("click", () => {
  setLanguage("es");
});

applyStaticTranslations();
updateKeyPanelState();
loadDashboard();